#!/bin/bash


tar cvf /tmp/backup.tar /etc /var

gzip /tmp/backup.tar

find /tmp/backup.tar.gz -mtime -1 -type f -print &> /dev/null

if [ $? -eq 0 ]
then
echo "Backup is created"
echo
echo "Archiving backup"
#scp /tmp/backup.tar.gz root@192.168.56.1.x:/path
else
echo "Backup not created"
fi
